# Install application dependencies
FROM node AS dependencies
ENV NODE_ENV development
WORKDIR /home/node/app
RUN ["npm", "install", "-g", "nodemon"]
COPY package*.json ./
RUN ["npm", "install"]

# Copy over the application files
FROM dependencies
COPY . ./
RUN ["chown", "-R", "node:node", "/home/node"]

# Set the application parameters
ENV PORT 3000
EXPOSE ${PORT}

# Set the default command to serve
USER node
CMD ["nodemon", "bin/www"]
